export default [
  'Actions speak louder than words, and yours tell an incredible story.',
  'Being around you is like being on a happy little vacation.',
  'Being around you makes everything better!',
  'Colours seem brighter when you\'re around.',
  'Everyone gets knocked down sometimes, but you always get back up and keep going.',
  'Everything would be better if more people were like you!',
  'Hanging out with you is always a blast.',
  'I appreciate you.',
  'I bet you make babies smile.',
  'I like your style.',
  'If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.',
  'If someone based an Internet meme on you, it would have impeccable grammar.',
  'Is that your picture next to \'charming\' in the dictionary?',
  'Jokes are funnier when you tell them.',
  'On a scale from 1 to 10, you\'re an 11.',
  'Our community is better because you\'re in it.',
  'The people you love are lucky to have you in their lives.',
  'When you say, \'I meant to do that,\' I totally believe you.',
  'You always know how to find that silver lining.',
  'You always know just what to say.',
  'You are brave.',
  'You are making a difference.',
  'You are the most perfect you there is.',
  'You bring out the best in other people.',
  'You have a great sense of humor.',
  'You have impeccable manners.',
  'You have the best ideas.',
  'You have the best laugh.',
  'You light up the room.',
  'You look great today.',
  'You should be proud of yourself.',
  'You should be thanked more often. So thank you!!',
  'You\'re a candle in the darkness.',
  'You\'re a gift to those around you.',
  'You\'re a great example to others.',
  'You\'re a great listener.',
  'You\'re a smart cookie.',
  'You\'re even better than a unicorn, because you\'re real.',
  'You\'re even more beautiful on the inside than you are on the outside.',
  'You\'re inspiring.',
  'You\'re like a breath of fresh air.',
  'You\'re like sunshine on a rainy day.',
  'You\'re one of a kind!',
  'You\'re really something special.',
  'You\'re so thoughtful.',
  'You\'re someone\'s reason to smile.',
  'You\'re wonderful.',
  'Your creative potential seems limitless.',
  'Your smile is contagious.'
] as const;
